// GitHub PR client — write path for mechanical fixes (PRD R4/§6.2). Opens a PR on a NEW
// branch; never merges (a human always reviews + merges). Ported from imagine-seo-engine's
// RepoClient (Octokit-based branch/commit/PR flow), adapted to this app's env conventions.
//
// IMPORTANT: this is currently pointed at a proof-of-concept target repo
// (Vyro-ai/imagine-motion-design-web), NOT the repo that actually renders the scanned
// imagine.art pages. So the PR content is a clearly-labeled proposal document (markdown),
// never a guessed edit to a real template file — there is no URL-to-source-file mapping for
// this target, and inventing one would be actively wrong.
import { Octokit } from "@octokit/rest";
import type { ChangeRequestPreview } from "./routing";

export interface FileChange {
  path: string;
  content: string;
}

export interface PullRequestResult {
  number: number;
  url: string;
  branch: string;
}

function targetRepo(): { owner: string; repo: string; baseBranch: string } {
  const full = process.env.TARGET_REPO;
  const baseBranch = process.env.TARGET_REPO_BASE_BRANCH || "main";
  if (!full) throw new Error("TARGET_REPO not set (expected 'owner/name' in .env.local).");
  const [owner, repo] = full.split("/");
  if (!owner || !repo) throw new Error(`Invalid TARGET_REPO "${full}" (expected "owner/name").`);
  return { owner, repo, baseBranch };
}

function client(): Octokit {
  const token = process.env.GITHUB_BOT_TOKEN;
  if (!token) throw new Error("GITHUB_BOT_TOKEN not set in .env.local.");
  return new Octokit({ auth: token });
}

/**
 * Creates `branch` off the base branch, commits `changes`, and opens a PR. Returns the PR
 * number + URL. Never merges — the PR sits open for human review.
 */
export async function openPullRequest(input: {
  branch: string;
  title: string;
  body: string;
  changes: FileChange[];
}): Promise<PullRequestResult> {
  const octokit = client();
  const { owner, repo, baseBranch } = targetRepo();

  const baseRef = await octokit.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
  const baseSha = baseRef.data.object.sha;
  const baseCommit = await octokit.git.getCommit({ owner, repo, commit_sha: baseSha });

  const blobs = await Promise.all(
    input.changes.map((change) =>
      octokit.git
        .createBlob({ owner, repo, content: change.content, encoding: "utf-8" })
        .then((blob) => ({ path: change.path, sha: blob.data.sha })),
    ),
  );

  const tree = await octokit.git.createTree({
    owner,
    repo,
    base_tree: baseCommit.data.tree.sha,
    tree: blobs.map((blob) => ({ path: blob.path, mode: "100644" as const, type: "blob" as const, sha: blob.sha })),
  });

  const commit = await octokit.git.createCommit({
    owner,
    repo,
    message: input.title,
    tree: tree.data.sha,
    parents: [baseSha],
  });

  await octokit.git.createRef({ owner, repo, ref: `refs/heads/${input.branch}`, sha: commit.data.sha });

  const pr = await octokit.pulls.create({
    owner,
    repo,
    title: input.title,
    body: input.body,
    head: input.branch,
    base: baseBranch,
  });

  return { number: pr.data.number, url: pr.data.html_url, branch: input.branch };
}

function slugify(s: string): string {
  return s.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase();
}

/**
 * Build the proposal markdown file for a PR-routed change request. This is a PROPOSAL
 * DOCUMENT, not an edit to a real source file — the target repo here is a proof-of-concept,
 * not the codebase that renders the audited pages.
 */
function proposalMarkdown(preview: ChangeRequestPreview, timestamp: string): string {
  return [
    `# ${preview.title}`,
    "",
    `_Generated by GenAI Scout's Indexing & Core Web Vitals tool — ${timestamp}._`,
    "",
    "> **Proof-of-concept PR.** This repo is a scratch target used to prove out the automated",
    "> branch → commit → PR flow. It is NOT the codebase that renders the audited pages, so",
    "> this PR proposes a fix rather than attempting to patch real template files.",
    "",
    preview.body,
  ].join("\n");
}

/** Open a proposal PR for one routing preview. Only call this from an explicit user action. */
export async function openProposalPr(
  preview: ChangeRequestPreview,
  timestamp: string,
): Promise<PullRequestResult> {
  const branch = `seo/${slugify(preview.reason)}-${Date.now()}`;
  const path = `seo-proposals/${slugify(preview.reason)}.md`;
  return openPullRequest({
    branch,
    title: preview.title,
    body: `${preview.body}\n\n---\n_Proposal file: \`${path}\`._`,
    changes: [{ path, content: proposalMarkdown(preview, timestamp) }],
  });
}
