import * as dotenv from "dotenv"; import { resolve } from "node:path";
dotenv.config({ path: resolve(import.meta.dirname, "../.env.local"), quiet: true });
const pg = (await import("pg")).default;
const c = new pg.Client({ connectionString: process.env.DATABASE_URL }); await c.connect();
await c.query(`DELETE FROM learned_sources WHERE type='domain'`); await c.end();
const { runLearningPhase, getPromotedLearnedDomains } = await import("../src/lib/learn/index.ts");
const r = await runLearningPhase();
const promoted = await getPromotedLearnedDomains();
console.log("learning result:", JSON.stringify(r));
console.log(`\nCLEANED auto-promoted domains feeding RSS (${promoted.length}):\n  ` + promoted.sort().join("\n  "));
process.exit(0);
